In [8]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv("Student_Performance.csv")
df.head()

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f

In [10]:
df.isnull().sum()

student_id               0
age                      0
gender                   0
school_type              0
parent_education         0
study_hours              0
attendance_percentage    0
internet_access          0
travel_time              0
extra_activities         0
study_method             0
math_score               0
science_score            0
english_score            0
overall_score            0
final_grade              0
dtype: int64

In [11]:
label_encoder = LabelEncoder()
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col] = label_encoder.fit_transform(df[col])

In [12]:
X = df.drop(["final_grade", "student_id"], axis=1)
y = df["final_grade"]

In [13]:
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled.head()

,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score
0,0.0,0.5,1.0,1.0,0.346667,0.686,1.0,0.666667,1.0,0.6,0.427,0.554,0.570,0.451462
1,0.8,0.0,1.0,0.2,0.426667,0.756,1.0,1.000000,0.0,1.0,0.576,0.688,0.648,0.547368
2,0.6,0.0,0.0,1.0,0.986667,0.310,0.0,0.666667,0.0,0.6,0.848,0.950,0.792,0.878363
3,0.4,1.0,1.0,0.4,0.080000,0.162,0.0,0.000000,0.0,0.6,0.444,0.275,0.547,0.316959
4,0.4,0.0,1.0,0.4,0.106667,0.220,1.0,0.333333,1.0,0.2,0.089,0.327,0.300,0.127485

In [14]:
processed_df = pd.concat([X_scaled, y.reset_index(drop=True)], axis=1)
processed_df.head()

,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,0.0,0.5,1.0,1.0,0.346667,0.686,1.0,0.666667,1.0,0.6,0.427,0.554,0.570,0.451462,4
1,0.8,0.0,1.0,0.2,0.426667,0.756,1.0,1.000000,0.0,1.0,0.576,0.688,0.648,0.547368,3
2,0.6,0.0,0.0,1.0,0.986667,0.310,0.0,0.666667,0.0,0.6,0.848,0.950,0.792,0.878363,1
3,0.4,1.0,1.0,0.4,0.080000,0.162,0.0,0.000000,0.0,0.6,0.444,0.275,0.547,0.316959,4
4,0.4,0.0,1.0,0.4,0.106667,0.220,1.0,0.333333,1.0,0.2,0.089,0.327,0.300,0.127485,5

In [15]:
train_data, test_data = train_test_split(
    processed_df,
    test_size=0.2,
    random_state=42
)

In [16]:
num_clients = 4
client_datasets = np.array_split(train_data, num_clients)

c:\Users\SRINIDHI\anaconda3\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [17]:
for i, client_data in enumerate(client_datasets):
    print(f"Client {i+1} dataset shape: {client_data.shape}")

Client 1 dataset shape: (5000, 15)
Client 2 dataset shape: (5000, 15)
Client 3 dataset shape: (5000, 15)
Client 4 dataset shape: (5000, 15)